export type Spirits = "Bourbon" | "Gin" | "Black Rum" | "White Rum" | "Vodka" | "Whiskey" | "Ruby Port Wine" | "Amaretto"

export type Mixers =
  | "Angostura Bitters"
  | "Aquafaba"
  | "Champagne"
  | "Coffee Liqueur"
  | "Creme de Violette"
  | "Demerara Syrup"
  | "Espresso"
  | "Ginger Beer"
  | "Lemon Juice"
  | "Lime Juice"
  | "Maraschino Liqueur"
  | "Mint Leaves"
  | "Raspberry Syrup"
  | "Simple Syrup"
  | "Soda Water"
  | "Thyme Syrup"
  | "Honey Syrup"
  | "Club Mate"

export type Garnishes = "Lemon Wedge" | "Lime Wedge" | "Mint Leaves" | "Orange Peel" | "Orange Wedge" | "Raspberry" | "Thyme"
